name: CI

on:
  repository_dispatch:
    types: [test_trigger]  
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run auto-archive
        run: |
          SLACK_TOKEN=$SLACK_TOKEN \
          DRY_RUN=$DRY_RUN \
          python slack_autoarchive.py
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          DRY_RUN: false
          DAYS_INACTIVE: 180
          WHITELIST_KEYWORDS: 'general,random,activity,times_'
          ADMIN_CHANNEL: activity
